name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      '**.py'

jobs:
  lint:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependency
        run: pip install ruff mypy
      - name: Run ruff
        run: ruff check src/neosca/ tests/
      - name: Run mypy
        run: mypy --check-untyped-defs src/neosca/
